### ISSUE TITLE
上传大文件时进度条始终是0%,是否是速度太慢

### ISSUE THREAD

**Issue by be-water-myFriend** [Soulghost/SGWiFiUpload#1]
作者您好,
      我测试您的demo,上传小文件时可以,大文件的时失败, 上传速度能否提升?

**Comment by Soulghost** [comment]
您好，上传速度确实较慢，只有1M~2M/s的样子，这样进度刚开始只有零点零零几，所以%.2f显示为0。模拟器和本地网络之间很快，但是真机慢得多，可能是因为真机或者网络设备的限制，不太好提高。

**Comment by be-water-myFriend** [comment]
您好,我测试过程中发现一个问题, 局域网内ping手机的时候延迟在80ms左右,路由器和手机均正常,在不同的机型和路由器上测试过, 会不会和wifi的信道有关系

**Comment by Soulghost** [comment]
这个我也不太清楚(●′ω`●) ，不好意思。

**Comment by be-water-myFriend** [comment]
谢谢你的耐心解答

**Comment by Soulghost** [comment]
没事没事，互相学习嘿嘿。
