### ISSUE TITLE
真机测试时 浏览器输入ip无效

### ISSUE THREAD

**Issue by insurgentZhao** [Soulghost/SGWiFiUpload#2]
您好，如题  请问是什么原因造成的  谢谢

**Comment by Soulghost** [comment]
您好，请检查一下浏览器所在的设备和真机是否处于同一网段内

**Comment by insurgentZhao** [comment]
您好   我固定了端口号   有的时候可以打开  有的时候就打不开   每次我查看的时候   ip前3段都是相同的。 而且连续点击的话有可能会出现   Error, Server Stopped ...感谢回答~

**Comment by Soulghost** [comment]
您好，Server Stopped是Demo的一个BUG，现在已经修复。
我更新了这个repo，现在支持以block形式回调，并且展示的WiFi Page在dismiss时提供了回调，以便关闭服务器。
最近比较忙，很抱歉回复较晚。

**Comment by hepking** [comment]
还是不行，这个问题

**Comment by xinge1** [comment]
换了个端口，可以了。真机测试

**Comment by yatoudage** [comment]
亲测，同一个wifi，用不了

**Comment by Soulghost** [comment]
这个问题来自于 iOS 10 开始出现的网络权限申请，由于 Sever App 没有主动的网络访问，而只是被动监听，这种情况下需要 App 主动访问一次网络，拿到网络权限后，即可解决，

**Comment by imnayandave** [comment]
It was still showing me error of duplicating command in "About.txt" and worked for me after deleting that file from my project.

它仍然显示我在“ About.txt”中复制命令的错误，并且在从我的项目中删除该文件后为我工作.

**Comment by Soulghost** [comment]
> It was still showing me error of duplicating command in "About.txt" and worked for me after deleting that file from my project.
> 
> 它仍然显示我在“ About.txt”中复制命令的错误，并且在从我的项目中删除该文件后为我工作.

Yes, it is because two About.txt in main bundle, one is Vendor/CocoaAsyncSocket/About.txt, another is Vendor/CocoaLumberjack/About.txt, there is not any namespace for them, now I have fix this problem by rename them.

Thanks for your report.

**Comment by imnayandave** [comment]
It's showing me "Error , your Device is not connected to WiFi" in simulator while it's connected to WiFi.
i need help
